<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>jacket</name>
   <tag></tag>
   <elementGuidId>21bff74f-3236-440b-affd-b76ebc6c0f14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#product-4 > img.product</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='product-4']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3391e807-d60d-44f2-bd58-4a88768ffc13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//sauce-demo.myshopify.com/cdn/shop/products/fleece_large.jpg?v=1394656989</value>
      <webElementGuid>2c1e3495-23fe-4bbc-bbc6-003f8e8c2055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Grey jacket</value>
      <webElementGuid>61eece4c-2106-4aec-8949-810bdd28f9f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product</value>
      <webElementGuid>e82a0872-cc2a-401f-ab5d-e216630197cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-4&quot;)/img[@class=&quot;product&quot;]</value>
      <webElementGuid>fcc2f2f8-ee80-4b34-b7e5-1ab568d2daa2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='product-4']/img</value>
      <webElementGuid>a5d568ac-2753-458c-8aba-89610dab3d3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Grey jacket']</value>
      <webElementGuid>988dd45c-5fdb-489a-aa6b-94886dba6615</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a/img</value>
      <webElementGuid>2ce82330-0c64-4073-aa36-3d27f1ec1105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//sauce-demo.myshopify.com/cdn/shop/products/fleece_large.jpg?v=1394656989' and @alt = 'Grey jacket']</value>
      <webElementGuid>990fc42e-388c-4f07-af9e-82d55385cad2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
