<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>qty</name>
   <tag></tag>
   <elementGuidId>ca084262-37b1-4c9b-b6b9-f934c0ecf6b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.one.columns.quantity.tr > #updates_611945025</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='updates_611945025'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>efe94778-9204-4046-8ddb-af9af5d93384</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>62479596-e1be-4835-afdc-f2cae643d117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>updates[]</value>
      <webElementGuid>d0bc001a-ad2f-4d84-9b85-79a1b15d5e97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>updates_611945025</value>
      <webElementGuid>c26dc980-4692-49aa-9da7-f43e4a77454a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>964e4317-89d1-49c6-976e-536db7972ebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cart&quot;)/form[1]/div[@class=&quot;twelve columns alpha omega&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;one columns quantity tr&quot;]/input[@id=&quot;updates_611945025&quot;]</value>
      <webElementGuid>6064b1fd-16cb-4ee9-b4e0-366951c02b81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='updates_611945025'])[2]</value>
      <webElementGuid>ce6c5e3a-0ff9-4655-b952-f32c7316305b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='cart']/form/div/div[2]/div[3]/input</value>
      <webElementGuid>45143ae0-f1eb-4958-9864-6146ed97c0b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/input</value>
      <webElementGuid>2c5cf58d-134f-42c0-b78f-c0db78320715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'updates[]' and @id = 'updates_611945025']</value>
      <webElementGuid>573d6c69-bd78-41f9-af20-6bbc9d759884</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
