<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Remove</name>
   <tag></tag>
   <elementGuidId>348411d3-4252-4fb3-8d52-c1d12bbfd580</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.one.column.remove.omega.desktop > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='cart']/form/div/div[2]/div[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1d74323f-1623-4008-94a5-8e705243ae41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/cart/change?line=1&amp;quantity=0</value>
      <webElementGuid>c85d3828-fff3-4578-8319-912ff952c47e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>x</value>
      <webElementGuid>d724dfd2-cb7a-4f57-a47d-033c7afd0ddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cart&quot;)/form[1]/div[@class=&quot;twelve columns alpha omega&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;one column remove omega desktop&quot;]/a[1]</value>
      <webElementGuid>f5904b8d-be4a-4701-a710-513f2962115f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='cart']/form/div/div[2]/div[5]/a</value>
      <webElementGuid>24fb4ae2-1c30-49c6-89b0-13b052474b15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'x')]</value>
      <webElementGuid>62d6ad96-41e7-40ad-af94-83997265cf5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='£39.99'])[4]/following::a[1]</value>
      <webElementGuid>21439cf0-31cd-4c84-bcce-d3de5c0d402e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='£39.99'])[3]/following::a[1]</value>
      <webElementGuid>0cee19b8-41fa-4269-81e3-296930d8e6b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='« Continue Shopping'])[1]/preceding::a[1]</value>
      <webElementGuid>447d1a6a-3814-49a7-b98f-13e4406e5fb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total £39.99'])[1]/preceding::a[2]</value>
      <webElementGuid>44a32c62-5a8b-4175-8034-427b1b171455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='x']/parent::*</value>
      <webElementGuid>e26da963-1955-4ccf-aa93-833113f2c3f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/cart/change?line=1&amp;quantity=0')])[2]</value>
      <webElementGuid>27936d46-1afc-4cd9-a41e-106858ae6bb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[5]/a</value>
      <webElementGuid>ce748a09-1459-4b45-9070-907260d651b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/cart/change?line=1&amp;quantity=0' and (text() = 'x' or . = 'x')]</value>
      <webElementGuid>d9e19477-0aed-40ef-8284-60590a7eee00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
