<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sandals</name>
   <tag></tag>
   <elementGuidId>7f773935-dfa0-431e-a0a6-db8ca3bfec49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#product-2 > img.product</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='product-2']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>191f0e88-9d35-4f29-8e15-a630664a6cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//sauce-demo.myshopify.com/cdn/shop/products/shoes_large.jpg?v=1394656541</value>
      <webElementGuid>f1c36bce-df67-4321-8dd8-a57474ca576d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Bronze sandals</value>
      <webElementGuid>15473f51-f616-4d11-96c8-e4538f82466d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product</value>
      <webElementGuid>db79d2b8-1ce7-4540-8455-05d5bc708c73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-2&quot;)/img[@class=&quot;product&quot;]</value>
      <webElementGuid>2e5301da-4992-4237-8471-ae6cf292f6c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='product-2']/img</value>
      <webElementGuid>0476b825-f1f9-43a1-84df-66586662739a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Bronze sandals']</value>
      <webElementGuid>db81e6f6-34d6-4e2a-ad74-c68dda4b5dba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/img</value>
      <webElementGuid>38f553b0-ce1e-46ad-81f4-7af869b7d39f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//sauce-demo.myshopify.com/cdn/shop/products/shoes_large.jpg?v=1394656541' and @alt = 'Bronze sandals']</value>
      <webElementGuid>f53cb0f1-ac10-4c98-823e-6e73982ca2c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
