<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>update</name>
   <tag></tag>
   <elementGuidId>040e43d4-2361-48ab-bff0-ca87d435172f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#update</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='update']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ddc0efbe-4d5e-48c7-85d4-bb76df25e350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>90f69a67-c378-4abf-91da-ed39ecbc03e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>update</value>
      <webElementGuid>b8b695c3-6133-41ed-babc-b9992a1075d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>update</value>
      <webElementGuid>5d9d0103-7e29-4823-9051-290aa1c098f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Update</value>
      <webElementGuid>6243ef60-65e8-46fc-b894-0d74485227ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;update&quot;)</value>
      <webElementGuid>94f8a0f8-456f-4dc2-8b86-fc58243ad745</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='update']</value>
      <webElementGuid>43002fc6-8913-4d4b-bc51-a4e7a2cb3fb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='cart']/form/div[3]/div[2]/input</value>
      <webElementGuid>ac650022-806a-46a1-81af-3d2f9e9b0bbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>487cdc5a-de79-49d8-bd99-1bdc01192000</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'update' and @name = 'update']</value>
      <webElementGuid>fee73a3d-6422-4e19-99e6-373880491fb3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
