<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Use shipping address as billing addr_8b1546</name>
   <tag></tag>
   <elementGuidId>1fae2f61-f097-4a40-bb7b-42f395d65c00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkout-pay-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='checkout-pay-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bdcaec1f-e9af-4ca0-b839-a15aa3a344e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-busy</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>257b1fcc-0617-4703-92e4-f33e3ae2ba91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>75ef1858-6859-4ae9-8920-6fcf52fca0f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkout-pay-button</value>
      <webElementGuid>f6fb406b-5f26-4f28-bc0d-5298f305580a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>7268768e-0a68-40eb-adf5-60d9ac112797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_1m2hr9ge _1m2hr9gd _1fragemuk _1fragemn2 _1fragemp4 _1fragemty _1fragemud _1fragemuf _1fragemu4 _1m2hr9g1p _1m2hr9g1l _1fragemoy _1m2hr9g1f _1m2hr9g1c _1fragemu3 _1fragemts _1m2hr9g1z _1m2hr9g1x _1m2hr9g16 _1m2hr9g13 _1m2hr9gh _1m2hr9gf _1fragem32 _1m2hr9g1w _1m2hr9g19 _1m2hr9g17 _1fragemq0 _1m2hr9g1k</value>
      <webElementGuid>1d215d1d-94c5-47f1-9c30-eb910720d712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pay now</value>
      <webElementGuid>4d9e7892-b4a2-49aa-b75e-75deff1c36ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkout-pay-button&quot;)</value>
      <webElementGuid>c33bcc20-da7e-49b1-9bc1-122390b4d881</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='checkout-pay-button']</value>
      <webElementGuid>4d5a9c4b-cff6-4a0e-b23e-314c85e59df7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-pay-button-section']/div/button</value>
      <webElementGuid>75f34854-f243-4921-ac8b-6b40ff2305d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use shipping address as billing address'])[1]/following::button[1]</value>
      <webElementGuid>dd6c3321-6349-4410-99cb-dc2a864f7851</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name on card'])[1]/following::button[1]</value>
      <webElementGuid>e80e268a-5d22-4d7e-b610-c590dfc86853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms of service'])[1]/preceding::button[2]</value>
      <webElementGuid>c3dd7fa0-95d0-4bef-a3d2-c6c6189cd211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/button</value>
      <webElementGuid>f8330fca-0ee3-43a9-bc1a-0fce1f90771f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'checkout-pay-button' and @type = 'submit' and (text() = 'Pay now' or . = 'Pay now')]</value>
      <webElementGuid>6b4a4112-c9a1-400b-9ea8-2ce82e0131a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
