<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cardnumber</name>
   <tag></tag>
   <elementGuidId>3f6c7bc5-b5b9-4364-9718-ff48914e598d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@name='number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@name='number']</value>
      <webElementGuid>593e8e3f-9caa-412d-83c4-19a0eec9463c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
