<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ceklis_Email_marketing</name>
   <tag></tag>
   <elementGuidId>3404fc29-1579-43dc-a406-5bbd9041d5ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#marketing_opt_in</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='marketing_opt_in']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ce9b7187-76e0-4e59-816c-f49e58fda273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d6bae2cf-75a9-4170-adfa-33f93e592e3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>marketing_opt_in</value>
      <webElementGuid>ce44d531-5d7a-42a9-a9a5-2ed3e752cdeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>marketing_opt_in</value>
      <webElementGuid>03d54f2f-71ff-418a-8d97-27ca6b802472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_1mmswk98 _1mmswk97 _1fragemqf _1fragemqd _1fragemqh _1fragemqb _1fragemrf _1fragemrb _1fragemrj _1fragemr7 _1fragemci _1fragemby _1fragemd2 _1fragembe _1fragemp4 _1fragem32 _1fragemq0 _1fragem2x _1fragemu9 _1fragemu3 _1fragemug _1mmswk99 _1fragemov _1mmswk9c _1mmswk9a _1fragemus</value>
      <webElementGuid>c0e2e00a-8159-4e5d-94f3-92e8d0a054be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;marketing_opt_in&quot;)</value>
      <webElementGuid>e047a90b-9ac8-4bed-a7fc-183bc232e718</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='marketing_opt_in']</value>
      <webElementGuid>75c801be-1299-4754-89b0-9b428014d3ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='Form477']/div/div/section/div/div/div/div/div[3]/div[2]/div/div/div/input</value>
      <webElementGuid>d54c6a24-2681-4a98-a40c-5134f15da200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>14a71d50-0709-4d63-9229-cb61d1f862dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'marketing_opt_in' and @name = 'marketing_opt_in']</value>
      <webElementGuid>4a3755f2-6195-4cd9-82d4-0631bb0a37c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
