<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ceklis_Phone (optional)_save_shipping_information</name>
   <tag></tag>
   <elementGuidId>b4f5dd78-5ae2-4e79-8a09-f714d7c314af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#save_shipping_information</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='save_shipping_information']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>48b82bfc-c3d0-483e-b3d4-4034740b63c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>2019d04a-bff9-44fa-88b0-f3c7939d8b42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>save_shipping_information</value>
      <webElementGuid>b9df7711-113a-4dc7-a2cf-e511547ab452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>save_shipping_information</value>
      <webElementGuid>07d260df-723f-4e55-bd57-6d537fb92e8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_1mmswk98 _1mmswk97 _1fragemqf _1fragemqd _1fragemqh _1fragemqb _1fragemrf _1fragemrb _1fragemrj _1fragemr7 _1fragemci _1fragemby _1fragemd2 _1fragembe _1fragemp4 _1fragem32 _1fragemq0 _1fragem2x _1fragemu9 _1fragemu3 _1fragemug _1mmswk99 _1fragemov _1mmswk9c _1mmswk9a _1fragemus</value>
      <webElementGuid>75b327f8-f665-4e9d-8f33-26a707a7323c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;save_shipping_information&quot;)</value>
      <webElementGuid>0bceb62d-8390-4747-9025-77a396790cbb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='save_shipping_information']</value>
      <webElementGuid>8c6d563e-b0c6-4d01-aec6-3d0c5060f6a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shippingAddressForm']/div/div/div[9]/div/div/input</value>
      <webElementGuid>8a81c4f6-6f33-4d18-989a-9b8ca5b90d92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/input</value>
      <webElementGuid>11bce446-2768-40a4-b88f-6c967a7bcc15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'save_shipping_information' and @name = 'save_shipping_information']</value>
      <webElementGuid>b5a7acbe-7fc7-4d37-80e3-5aefc27a0e86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
