<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ceklis_Name on card_billingAddress</name>
   <tag></tag>
   <elementGuidId>b431f14f-1f9f-4272-aaed-74f0aee48087</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#billingAddress</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billingAddress']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9253c9c6-686b-41cd-92fe-fbf51a4958d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a29b59bc-2978-4b95-8900-5e94220d887f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billingAddress</value>
      <webElementGuid>9385164f-2099-4440-8826-0259f50deaf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billingAddress</value>
      <webElementGuid>21d16ebc-0108-41f8-bae6-a3ec2552c3a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_1mmswk98 _1mmswk97 _1fragemqf _1fragemqd _1fragemqh _1fragemqb _1fragemrf _1fragemrb _1fragemrj _1fragemr7 _1fragemci _1fragemby _1fragemd2 _1fragembe _1fragemp4 _1fragem32 _1fragemq0 _1fragem2x _1fragemu9 _1fragemu3 _1fragemug _1mmswk99 _1fragemov _1mmswk9c _1mmswk9a _1fragemus</value>
      <webElementGuid>b602ca3d-b863-4f4b-967c-49420c651d74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billingAddress&quot;)</value>
      <webElementGuid>cddfb38b-da83-4b4c-b9d3-359e48f7edd3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billingAddress']</value>
      <webElementGuid>01ab1e74-41b5-4742-b6b8-3767621ac095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='directPaymentMethodDetails']/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>1dc5372c-c58d-4420-bd11-bebd54f84fdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>e0eb1b4d-4164-47a7-b223-fba27674241f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'billingAddress' and @name = 'billingAddress']</value>
      <webElementGuid>4cf44efd-633e-4c6b-af9a-6be617d28339</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
