<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>company</name>
   <tag></tag>
   <elementGuidId>7e3cb6d0-f407-4f7f-a18e-ad475b1c2812</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@name='company']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@name='company']</value>
      <webElementGuid>ed7671a1-6a1c-4b4d-a41b-d2d7c5e6960c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
