<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Security code_card-fields-verificati_967290</name>
   <tag></tag>
   <elementGuidId>73ad588f-8067-4ba9-94af-156b63fe3660</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#card-fields-verification_value-1hirhnya4b200000</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='card-fields-verification_value-1hirhnya4b200000']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>d6284e20-4b3a-4101-a845-8a1ab12cf7c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-fields-iframe</value>
      <webElementGuid>f115c67f-a1e7-41bc-a519-599b9f1650af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>20892b02-80c3-433e-9199-b7bf474fe0b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>card-fields-verification_value-1hirhnya4b200000</value>
      <webElementGuid>b9134221-dc11-4ba9-a896-0ae734c9629a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>card-fields-verification_value-1hirhnya4b200000</value>
      <webElementGuid>dd558a3e-1da9-448b-995b-f9bd5e981d32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>f82327be-62c5-4f90-b8f8-3baec105493c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://checkout.pci.shopifyinc.com/build/7c81d3e/verification_value-ltr.html?identifier=&amp;locationURL=</value>
      <webElementGuid>e6a5e052-4c00-4477-8454-4e7a989f62f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Field container for: Security code</value>
      <webElementGuid>d1c0c574-ed3f-4649-8366-7ff0e29af9f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;card-fields-verification_value-1hirhnya4b200000&quot;)</value>
      <webElementGuid>1b2c5980-4527-4f4c-aca7-83f761274ffa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='card-fields-verification_value-1hirhnya4b200000']</value>
      <webElementGuid>a5340ed7-107a-4816-943d-c07220fac40d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='verification_value']/iframe</value>
      <webElementGuid>3bacee95-1e06-4401-a069-85c8d3391e5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/iframe</value>
      <webElementGuid>2ebdc832-36ae-4a24-9cb7-490878c1c95e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'card-fields-verification_value-1hirhnya4b200000' and @name = 'card-fields-verification_value-1hirhnya4b200000' and @src = 'https://checkout.pci.shopifyinc.com/build/7c81d3e/verification_value-ltr.html?identifier=&amp;locationURL=' and @title = 'Field container for: Security code']</value>
      <webElementGuid>bc0e9185-ca60-4890-acd6-0ddfaf20b887</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
