<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_card</name>
   <tag></tag>
   <elementGuidId>d0dfbc7e-02db-4072-a2c5-87243df7e3ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//iframe[@class='card-fields-iframe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//iframe[@class='card-fields-iframe']</value>
      <webElementGuid>49058bc4-3163-45c8-864a-fb842d221802</webElementGuid>
   </webElementProperties>
</WebElementEntity>
