<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Name on card</name>
   <tag></tag>
   <elementGuidId>e5863512-a169-4f4f-97db-87bedd872559</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='card-fields-name-zbqomf0taw000000']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#card-fields-name-zbqomf0taw000000</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>c7dd6df0-fdbf-418d-a4be-437cbc164177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-fields-iframe</value>
      <webElementGuid>86e47e99-694c-4f9d-b076-f1a55bcafbfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>668fbf7e-5ed6-4eec-9811-20012f9a1dae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>card-fields-name-zbqomf0taw000000</value>
      <webElementGuid>18d50145-b0da-4ce1-8650-946ca1b9e81e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>card-fields-name-zbqomf0taw000000</value>
      <webElementGuid>f34e2c6a-d60e-46fc-ab32-ea3de829a91e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>0e01a40c-da08-45ac-ab73-2a9fa2c1087a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://checkout.pci.shopifyinc.com/build/7c81d3e/name-ltr.html?identifier=&amp;locationURL=</value>
      <webElementGuid>cde56941-e473-472c-b75d-812579e82cbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Field container for: Name on card</value>
      <webElementGuid>1db596b9-ca43-45f3-bdf6-c079d7f440b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;card-fields-name-zbqomf0taw000000&quot;)</value>
      <webElementGuid>0cb5c8d6-6526-499e-bd1c-cb97c23a9bd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='card-fields-name-zbqomf0taw000000']</value>
      <webElementGuid>9bc38809-dad4-4dce-837a-d76c03642708</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='name']/iframe</value>
      <webElementGuid>c79a8c34-e958-4b9c-bf0e-5cd834477e22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/iframe</value>
      <webElementGuid>4a55d63a-6725-42bf-b8c7-d26730bfa503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'card-fields-name-zbqomf0taw000000' and @name = 'card-fields-name-zbqomf0taw000000' and @src = 'https://checkout.pci.shopifyinc.com/build/7c81d3e/name-ltr.html?identifier=&amp;locationURL=' and @title = 'Field container for: Name on card']</value>
      <webElementGuid>b0ded1d3-bd7e-454f-b729-646e6f0709bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
