<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Expiration date (MM YY)</name>
   <tag></tag>
   <elementGuidId>b4f6b454-0586-47cc-a790-792a9c7cf57a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='card-fields-expiry-0kpae7mqbncl0000']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#card-fields-expiry-0kpae7mqbncl0000</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>85070d2b-157b-4bc7-abc4-14876362c291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-fields-iframe</value>
      <webElementGuid>9e820904-4083-404b-a500-ff7d809f033c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d185fe48-5366-4103-917e-fefd1b60e76e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>card-fields-expiry-0kpae7mqbncl0000</value>
      <webElementGuid>1d114cbf-047b-445b-9fde-cb09b836f0b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>card-fields-expiry-0kpae7mqbncl0000</value>
      <webElementGuid>74a902e8-9dff-4b3c-a79b-0a5affc49015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>6fbbd980-b984-422a-a97b-89f76e8e8434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://checkout.pci.shopifyinc.com/build/7c81d3e/expiry-ltr.html?identifier=&amp;locationURL=</value>
      <webElementGuid>397c0c19-13b0-407e-831d-5cfa0d08bcba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Field container for: Expiration date (MM / YY)</value>
      <webElementGuid>d21acf95-c505-41de-9b48-b5ccfb3b7a84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;card-fields-expiry-0kpae7mqbncl0000&quot;)</value>
      <webElementGuid>8837f48d-e612-413f-9a10-a6198e1b33fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='card-fields-expiry-0kpae7mqbncl0000']</value>
      <webElementGuid>cd158423-c38a-4dd6-81d5-5f5a2dc65e83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='expiry']/iframe</value>
      <webElementGuid>b30f4be4-978f-4905-a47c-4ba430f50bf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/iframe</value>
      <webElementGuid>acf77b53-94bc-4b7f-a737-3f8264c6af6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'card-fields-expiry-0kpae7mqbncl0000' and @name = 'card-fields-expiry-0kpae7mqbncl0000' and @src = 'https://checkout.pci.shopifyinc.com/build/7c81d3e/expiry-ltr.html?identifier=&amp;locationURL=' and @title = 'Field container for: Expiration date (MM / YY)']</value>
      <webElementGuid>5d7a8a3a-37dd-453f-8541-fed442daa82a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
