<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Card number</name>
   <tag></tag>
   <elementGuidId>dc5afe42-0cd1-450f-95b9-0714b4f9cda3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='card-fields-number-a3bcv87ph9o00000']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#card-fields-number-a3bcv87ph9o00000</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>40459e89-45ea-44f4-9fea-b0aa93290a50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-fields-iframe</value>
      <webElementGuid>26d68e78-b597-45f3-84f4-9dc4b62c8794</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>42c2db51-2832-4f66-9ac5-6305f6cca443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>card-fields-number-a3bcv87ph9o00000</value>
      <webElementGuid>754a7d82-8fdd-4644-924a-ae327c746ed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>card-fields-number-a3bcv87ph9o00000</value>
      <webElementGuid>1a7ff4b7-9988-42e6-ba3d-5ab474022be3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>3eb3cc7c-d524-4dad-baf1-3144e074e55b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://checkout.pci.shopifyinc.com/build/7c81d3e/number-ltr.html?identifier=&amp;locationURL=</value>
      <webElementGuid>003d18d7-8b2f-425e-b26f-a19730cc8d20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Field container for: Card number</value>
      <webElementGuid>d588bc9f-c267-449f-a207-0da7d3448428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;card-fields-number-a3bcv87ph9o00000&quot;)</value>
      <webElementGuid>cec311d4-9ce8-47bc-b248-8a0931f589cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='card-fields-number-a3bcv87ph9o00000']</value>
      <webElementGuid>07959320-d19f-42ac-85ee-f9715b862cef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='number']/iframe</value>
      <webElementGuid>16247a40-87e1-4f7b-8590-11a7dac69787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>9bf26cf4-5938-4688-adbd-369e20d6e8c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'card-fields-number-a3bcv87ph9o00000' and @name = 'card-fields-number-a3bcv87ph9o00000' and @src = 'https://checkout.pci.shopifyinc.com/build/7c81d3e/number-ltr.html?identifier=&amp;locationURL=' and @title = 'Field container for: Card number']</value>
      <webElementGuid>2bade96e-5c65-4be2-9c55-531de2b604a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
