<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Security code_verification_value</name>
   <tag></tag>
   <elementGuidId>881a2bea-fa2e-42c1-8fa8-cdc62b13c909</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#verification_value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='verification_value']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eb090ea0-6b4b-4174-ba88-f10161dd81b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>cc-csc</value>
      <webElementGuid>a809feb6-5f31-4ed3-9a6e-3e11c59e1bda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>verification_value</value>
      <webElementGuid>ebac4bd9-482e-4a84-9b62-6016407255f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>verification_value</value>
      <webElementGuid>798003c6-319a-4f7a-8f1a-56039fe16469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a5a78ded-9641-4a23-9fd4-5dee6df0b22a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>421ce404-2970-4d0c-8ca0-c1092f70a73d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]*</value>
      <webElementGuid>4c724fee-fe34-4665-9103-ba18e50bcb29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>error-for-verification_value tooltip-for-verification_value</value>
      <webElementGuid>a9c5342c-390f-4352-b767-815b704156f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-current-field</name>
      <type>Main</type>
      <value>verification_value</value>
      <webElementGuid>98c3e00b-3f73-487b-992e-21bef861f62d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-placeholder-color--lvl-22</value>
      <webElementGuid>8dbd8d9f-56ab-40b7-a191-00bb68c76fb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Security code</value>
      <webElementGuid>ac9041dc-9ac6-46b9-9c1f-82b8f680e28e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>863b08cb-9a40-42a8-a321-b54dbeb5569c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;verification_value&quot;)</value>
      <webElementGuid>a1ee8e11-d6e0-48a5-ac73-56a49c1547bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Checkout - Sauce Demo/iframe_Security code_card-fields-verificati_967290</value>
      <webElementGuid>1f603e43-3b01-45e2-8b9a-c75a9b9675ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='verification_value']</value>
      <webElementGuid>ad3fd6ea-7297-4e4c-b08d-b8adb806cf77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>04e9bb1f-0926-494c-b566-20f4dd1ba6b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'verification_value' and @name = 'verification_value' and @type = 'text' and @placeholder = 'Security code']</value>
      <webElementGuid>48201d47-859b-49b9-ab93-05a3bfdeb24a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
