<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address_Text</name>
   <tag></tag>
   <elementGuidId>bf6a4c62-fee2-448a-882f-b6e3b1408508</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TextField21</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TextField21']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ed1e7ba5-7a12-4ff8-8be8-f88d982a5161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TextField21</value>
      <webElementGuid>80943a28-e76b-4edc-962d-09ffc35b9b18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address1</value>
      <webElementGuid>5823aaa9-ce1f-4207-ac09-b2c272aff210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Address</value>
      <webElementGuid>55d85519-de80-44ca-aa6d-7ea9fdefef42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b985cacb-8c6d-4ea5-92df-72b7965a20f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3e8acc76-dd80-4972-8662-73d2f85e7377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>TextField21-label</value>
      <webElementGuid>e9209d60-d2fa-4b91-a392-250384028917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>shipping address-line1</value>
      <webElementGuid>53bdd492-db69-4b00-a418-2a22922f2fcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_7ozb2uq _7ozb2up _1fragemn2 _1fragemun _1fragemq0 _1fragemtt _7ozb2ut _7ozb2us _1fragemu9 _1fragemu4 _1fragemuj _7ozb2u11 _7ozb2u16 _7ozb2u1o _7ozb2ur</value>
      <webElementGuid>14962c16-172f-4146-8c03-68a8bdc14590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TextField21&quot;)</value>
      <webElementGuid>ee1be4b3-cdee-4321-ae34-30019dc4e15d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TextField21']</value>
      <webElementGuid>84805016-5621-4e77-8ce4-a9d40e59e5aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shippingAddressForm']/div/div/div[4]/div/div/div/div/div/input</value>
      <webElementGuid>d5874275-8609-429b-8603-63b7e6b12168</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/input</value>
      <webElementGuid>d43f9539-7399-49c2-9eac-9ad5e0d3462b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'TextField21' and @name = 'address1' and @placeholder = 'Address' and @type = 'text']</value>
      <webElementGuid>89a93728-3f2c-4cb4-80dc-bd8cdd95ec62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
