<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_City_Text</name>
   <tag></tag>
   <elementGuidId>21dbe1dc-8947-446b-be15-ccfe06b857bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TextField22</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TextField22']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c3200674-255c-4645-a48e-f7a5bae5d1f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TextField22</value>
      <webElementGuid>7c1c98b0-7191-46b9-8667-c5624e150228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>city</value>
      <webElementGuid>d0409fa7-0dc9-4241-94dd-d67085cd7e5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>City</value>
      <webElementGuid>b66cbccf-1fe5-40a7-854d-bd405da5092e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>78a713a4-808e-487f-b1ce-810f7e62abf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>741e678c-292e-4862-9fbb-5170cea63d3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>TextField22-label</value>
      <webElementGuid>8f0af37d-98fc-44d4-a20a-19c5fd32ba7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>shipping address-level2</value>
      <webElementGuid>2c67315d-8c1d-4b25-a84a-446e9ca7cc8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_7ozb2uq _7ozb2up _1fragemn2 _1fragemun _1fragemq0 _1fragemtt _7ozb2ut _7ozb2us _1fragemu9 _1fragemu4 _1fragemuj _7ozb2u11 _7ozb2u16 _7ozb2u1o _7ozb2ur</value>
      <webElementGuid>89ae4cfa-003f-459f-b4e9-75035ac29cf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TextField22&quot;)</value>
      <webElementGuid>e75315e2-4c73-49ce-95b9-27fc9cadf392</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TextField22']</value>
      <webElementGuid>a9442a59-1361-4a8b-9923-b9be4dd18295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shippingAddressForm']/div/div/div[6]/div/div/div/input</value>
      <webElementGuid>ef1ef1c1-72bb-42a1-8d1b-dabfe192d857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/input</value>
      <webElementGuid>73d1cd60-6a8d-48d6-b5a4-2e476d2c7e27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'TextField22' and @name = 'city' and @placeholder = 'City' and @type = 'text']</value>
      <webElementGuid>5e301cb2-3929-4dfd-85da-4aa356c105db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
