<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Discount code</name>
   <tag></tag>
   <elementGuidId>555961aa-c5d8-404a-8e18-cfa0012fff5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ReductionsInput254</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ReductionsInput254']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>040d9457-58c7-4360-b434-01ebf4b0f38a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ReductionsInput254</value>
      <webElementGuid>08d34de4-7484-4c17-b34a-938441eb28a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reductions</value>
      <webElementGuid>62fb3364-154c-4ca6-9373-2aed9e1b5eee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Discount code</value>
      <webElementGuid>c5315022-28cf-4025-a297-025e604bb238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6f4e1cda-866f-4997-aaca-9c49dc84627f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>ReductionsInput254-label</value>
      <webElementGuid>c617cffe-e1b1-4140-a07c-46c931483778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>16a45efb-9e04-45a3-87c4-81ccff953671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_7ozb2uq _7ozb2up _1fragemn2 _1fragemun _1fragemq0 _1fragemtt _7ozb2ut _7ozb2us _1fragemu9 _1fragemu4 _1fragemuj _7ozb2u11 _7ozb2u16 _7ozb2u1o _7ozb2ur</value>
      <webElementGuid>be83cab4-6a00-459f-a224-a4a82430ecd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ReductionsInput254&quot;)</value>
      <webElementGuid>16690456-0e36-469d-baef-2c1205f409aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ReductionsInput254']</value>
      <webElementGuid>9d04e8f9-fa3d-4ac6-9018-172f0341abea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='Form478']/div/div/div/div/div/input</value>
      <webElementGuid>d68a2929-a97c-4b96-a72d-52195ee764f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div/input</value>
      <webElementGuid>f3709cf9-5acf-4529-ae2f-ef18223ff9bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ReductionsInput254' and @name = 'reductions' and @placeholder = 'Discount code' and @type = 'text']</value>
      <webElementGuid>4e34e9a1-73c8-4a6e-b420-a356f80af473</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
