<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Company (optional)</name>
   <tag></tag>
   <elementGuidId>1752337f-d27d-4187-9964-8423caad41c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TextField1533</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TextField1533']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>53474ada-b11a-4b63-bd48-a28138cb3294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TextField1533</value>
      <webElementGuid>0db9d7b3-2a85-4517-8267-ad89b8531d50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>company</value>
      <webElementGuid>724513e3-ce80-4c57-98c5-ecfec5295e0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Company (optional)</value>
      <webElementGuid>afb0843a-829a-406b-8b4c-c8bb6b5a5694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e4190a13-c100-43bf-87b5-565df5cc889d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1ae71b34-7364-4624-ac53-f1365057ceac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>TextField1533-label</value>
      <webElementGuid>b628e2c5-66d8-4805-be8a-de4fb950857c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>shipping organization</value>
      <webElementGuid>d7a67ede-97ab-48c3-8484-17abb4c1b850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_7ozb2uq _7ozb2up _1fragemn2 _1fragemun _1fragemq0 _1fragemtt _7ozb2ut _7ozb2us _1fragemu9 _1fragemu4 _1fragemuj _7ozb2u11 _7ozb2u16 _7ozb2u1o _7ozb2ur</value>
      <webElementGuid>35dc448e-d0e4-47da-910f-3e484d0ba759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TextField1533&quot;)</value>
      <webElementGuid>e7565998-6505-42b4-a214-849ecac976ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TextField1533']</value>
      <webElementGuid>886b65c0-b395-4e69-b3cc-88cc21dfda7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shippingAddressForm']/div/div/div[3]/div/div/div/input</value>
      <webElementGuid>c1019ad1-d23d-4adc-b2c5-bfef0c5e2064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>885acfcc-e6af-47a5-847c-b575a5c51be9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'TextField1533' and @name = 'company' and @placeholder = 'Company (optional)' and @type = 'text']</value>
      <webElementGuid>99004a7d-0ff3-4a93-8100-670664b56559</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
