<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Postal code_Text</name>
   <tag></tag>
   <elementGuidId>c9ee3904-023d-42bf-be29-0d9f24db4952</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TextField23</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TextField23']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>69e5da42-ef57-4a31-a030-a46d0a984550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TextField23</value>
      <webElementGuid>3b0d2acb-9591-4917-b4cd-ec796fb40710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>postalCode</value>
      <webElementGuid>aa4ddd30-4a89-4d8f-84c3-b279e045c6ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Postal code</value>
      <webElementGuid>ee6a0f2c-9a8a-4139-ba1a-c5767a6547c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>08b4d5e9-747d-4dac-b66e-2adc32bcaed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>20065f2f-2f56-4e98-9341-aef20a38c5e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ee050d07-d77c-4aa9-b03d-82d279ec7b88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>TextField23-label</value>
      <webElementGuid>4c026a78-304a-4186-8adb-0a481fe6a136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>shipping postal-code</value>
      <webElementGuid>0be5315a-3d8c-4e34-9843-e97686dbeb47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>characters</value>
      <webElementGuid>78002f40-727e-49cc-8808-092941d929be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_7ozb2uq _7ozb2up _1fragemn2 _1fragemun _1fragemq0 _1fragemtt _7ozb2ut _7ozb2us _1fragemu9 _1fragemu4 _1fragemuj _7ozb2u11 _7ozb2u16 _7ozb2u1o _7ozb2ur</value>
      <webElementGuid>c3e95e19-1209-4f82-82e8-233ebc069cfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TextField23&quot;)</value>
      <webElementGuid>6a560322-573b-45bc-9002-8f1c6f5aee93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TextField23']</value>
      <webElementGuid>11cb12c2-1f86-4e37-a541-ce1b116e4e77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shippingAddressForm']/div/div/div[7]/div[2]/div/div/div/input</value>
      <webElementGuid>a82bf353-5695-4d8a-84e8-19f65d550a6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div/div/div/input</value>
      <webElementGuid>110f5157-33cb-435d-8817-a4af6fb58166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'TextField23' and @name = 'postalCode' and @placeholder = 'Postal code' and @type = 'text']</value>
      <webElementGuid>d0d6f8b5-3ec7-44d0-8022-fea2f07e95ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
