<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>province</name>
   <tag></tag>
   <elementGuidId>c6be8a33-4b32-4602-a708-bb6d14aaa03c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//select[@name='zone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[@name='zone']</value>
      <webElementGuid>5866ae7a-2930-4669-a8fb-31d1bda68d9b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
