<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_CountryRegion</name>
   <tag></tag>
   <elementGuidId>19ea7960-0510-4b77-9763-c03082680e0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Select0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Select319</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'countryCode' and @id = 'Select0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>43bd59a8-3b3e-44f3-b47a-90c62f8304c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>countryCode</value>
      <webElementGuid>f4bf66be-3de8-4d11-9ccf-4b5d44e0672d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Select0</value>
      <webElementGuid>0bbaf620-63ab-4885-8d96-cab8e36ce03b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>shipping country</value>
      <webElementGuid>f8e3899c-dc21-4c02-ac9c-a810003fe062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ZHJU6 _1k3449n5 _1k3449n3 _1fragemus oAlPg IWR5K tu1VS</value>
      <webElementGuid>241da976-de16-4a36-8579-5c5fb0096ac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Select0&quot;)</value>
      <webElementGuid>0fe8ac92-e999-426e-8b8f-2f1358a0acea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Select0']</value>
      <webElementGuid>eddb67ac-ec35-4795-810d-f7ad2f0d0449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shippingAddressForm']/div/div/div/div/div/div/select</value>
      <webElementGuid>6949d469-73b7-434a-8cbd-624827b83319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country/Region'])[1]/following::select[1]</value>
      <webElementGuid>f0990e2b-75a5-46bc-8c88-22ea2f249e74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delivery'])[1]/following::select[1]</value>
      <webElementGuid>83f35ebd-62fd-4577-98c7-2de1ff3b926a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First name (optional)'])[1]/preceding::select[1]</value>
      <webElementGuid>6be1baaa-c78b-42ae-97d9-593f5308f803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last name'])[1]/preceding::select[1]</value>
      <webElementGuid>c8da507f-8122-4117-9c8a-45b3db045c2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>2d720d63-71ff-423c-83af-779963d0778c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id='Select0' and @name='countryCode']</value>
      <webElementGuid>babef069-d053-4752-85cf-139645cabf0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
