<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Province</name>
   <tag></tag>
   <elementGuidId>b5658249-81b1-4880-9c33-a9e548663ab4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Select6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Select6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>77071e76-9b79-4ffa-8087-e1202f30a57f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>zone</value>
      <webElementGuid>e5c5ec80-adc2-4a7d-9aed-87f30a272761</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Select6</value>
      <webElementGuid>6b50e1ef-c150-4677-9732-09bb4a2b952c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>shipping address-level1</value>
      <webElementGuid>8149c7ac-98f7-474a-b4cc-f8d7922d82c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ZHJU6 _1k3449n5 _1k3449n3 _1fragemus oAlPg IWR5K tu1VS</value>
      <webElementGuid>5dbd6ca3-cb80-46d8-ba72-9f3ffa8075b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> AcehBaliBangka–Belitung IslandsBantenBengkuluGorontaloJakartaJambiWest JavaCentral JavaEast JavaWest KalimantanSouth KalimantanCentral KalimantanEast KalimantanNorth KalimantanRiau IslandsLampungMalukuNorth MalukuNorth SumatraWest Nusa TenggaraEast Nusa TenggaraPapuaWest PapuaRiauSouth SumatraWest SulawesiSouth SulawesiCentral SulawesiSoutheast SulawesiNorth SulawesiWest SumatraYogyakarta</value>
      <webElementGuid>5a851f9f-d413-4912-8bac-c439317d49e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Select6&quot;)</value>
      <webElementGuid>42f3d45e-a5f1-4490-9ada-665c1f962eaf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Select6']</value>
      <webElementGuid>c00b04c2-5f81-484b-ba2f-064e82ebbeee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shippingAddressForm']/div/div/div[7]/div/div/div/select</value>
      <webElementGuid>40b0fad2-0ad9-44b7-9444-684fa209dec2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Province'])[1]/following::select[1]</value>
      <webElementGuid>9b7c224c-6e83-43b9-8fe1-be570a13ecd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='City'])[1]/following::select[1]</value>
      <webElementGuid>e71cd0c2-dd27-425c-bb4f-de5db1ff6d7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Postal code'])[1]/preceding::select[1]</value>
      <webElementGuid>5a518832-d822-4c03-bc1c-e8e3fdbb683f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone (optional)'])[1]/preceding::select[1]</value>
      <webElementGuid>bbf67a38-60a5-4f59-b3ca-1184c669c660</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/select</value>
      <webElementGuid>0b72e678-2ff1-49c0-bff1-0f61d9e9f0ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'zone' and @id = 'Select6' and (text() = ' AcehBaliBangka–Belitung IslandsBantenBengkuluGorontaloJakartaJambiWest JavaCentral JavaEast JavaWest KalimantanSouth KalimantanCentral KalimantanEast KalimantanNorth KalimantanRiau IslandsLampungMalukuNorth MalukuNorth SumatraWest Nusa TenggaraEast Nusa TenggaraPapuaWest PapuaRiauSouth SumatraWest SulawesiSouth SulawesiCentral SulawesiSoutheast SulawesiNorth SulawesiWest SumatraYogyakarta' or . = ' AcehBaliBangka–Belitung IslandsBantenBengkuluGorontaloJakartaJambiWest JavaCentral JavaEast JavaWest KalimantanSouth KalimantanCentral KalimantanEast KalimantanNorth KalimantanRiau IslandsLampungMalukuNorth MalukuNorth SumatraWest Nusa TenggaraEast Nusa TenggaraPapuaWest PapuaRiauSouth SumatraWest SulawesiSouth SulawesiCentral SulawesiSoutheast SulawesiNorth SulawesiWest SumatraYogyakarta')]</value>
      <webElementGuid>8a2391b3-1f1d-4797-bcb5-2fd79dff8a6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
