<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email Address</name>
   <tag></tag>
   <elementGuidId>b1c9ac1d-3ea4-41ac-806b-2ee4fa87debe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#customer_email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='customer_email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a39e1900-5098-420a-b88c-37e386a40617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>21bf22d6-c7af-46e2-8209-e029d91190ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customer[email]</value>
      <webElementGuid>6d200c63-c522-485b-8006-7da1d98164e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>customer_email</value>
      <webElementGuid>c5e007d7-2563-447a-ba0a-97dbf0f18200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>long</value>
      <webElementGuid>92b8aa22-28ec-4b2f-a18a-0a353cc07424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customer_email&quot;)</value>
      <webElementGuid>d761876a-8527-4805-bf12-3ed761bfeb7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='customer_email']</value>
      <webElementGuid>1921f8e1-6597-4e72-b04b-f9f1404dcde7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login_email']/input</value>
      <webElementGuid>18b3278f-69a3-4f74-b677-3ecf2660bb2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>805f542c-d70f-4d85-ac60-a8328568101b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'customer[email]' and @id = 'customer_email']</value>
      <webElementGuid>4036f5ec-febe-4b0b-a565-c855634af1c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
