<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>signin_button</name>
   <tag></tag>
   <elementGuidId>0356dbad-c978-426f-8bdb-f6981188b8e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Sign In']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d715ba03-d68c-4fea-9155-844e30f3dbff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>c8254b2d-237b-47ac-bd22-a5c16b13a1af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>970cd05e-52d0-4f02-9e0c-c7ee4039c332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Sign In</value>
      <webElementGuid>e559f5d1-233b-4c40-9443-fffd203c659b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customer_login&quot;)/div[@class=&quot;action_bottom&quot;]/input[@class=&quot;button&quot;]</value>
      <webElementGuid>5022923f-f2c2-4f5d-8543-e984acc106a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Sign In']</value>
      <webElementGuid>48bfc7e5-6f6a-41bb-87e8-6de8409a83e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='customer_login']/div[5]/input</value>
      <webElementGuid>c84546af-da29-47a1-8157-922dbe0170cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>4da61db6-2e9e-4090-9d75-5bb61cfe48ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>d9485d7e-e54d-48a7-9da1-53923fa5e253</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
