<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_39.99_add</name>
   <tag></tag>
   <elementGuidId>5908f1f2-4eb5-4a22-b962-c6140672e875</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#add</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='add']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5cec2d23-9fe8-4e29-b878-c7a37bd23f37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>8edfcd18-18c1-4f3a-8f58-655135687468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Add to Cart</value>
      <webElementGuid>80828641-3877-44b9-a5ec-dea538494404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add</value>
      <webElementGuid>04f9e45b-d4dc-4b11-ad8a-a7bdbc624de3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn add-to-cart</value>
      <webElementGuid>e79578ee-78aa-41a9-be27-2bdca07233f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add&quot;)</value>
      <webElementGuid>e8cccb05-3dc5-4e43-9ffd-e21a3918affa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='add']</value>
      <webElementGuid>4f54fa66-39dd-4632-9730-9f0c86392574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product-form']/input</value>
      <webElementGuid>3a99a4e6-85b4-4349-88d1-0263b5ef785d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/form/input</value>
      <webElementGuid>0732a026-b459-4fbe-91a2-cfd0e08599eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'add']</value>
      <webElementGuid>ee85634c-6d67-4860-86f9-0338e8b3310f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
